version: "3"
services:
  create_pdf:
      build: . # use this to build the local Dockerfile
      # image: andygrunwald/fom-latex-template # use this to build from the image
      volumes:
        - ./:/data
      command: bash scripts/compile.sh
  watch:
    build: .
    volumes:
      - ./:/data
    command: bash scripts/watch.sh
  
  pdf_server:
    build: .
    volumes:
      - ./:/data
    command: bash scripts/pdf_server.sh
    ports:
      - "3543:3543"
    expose:
      - 3543